spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jmx:
    default-domain: newIndiepostEb
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    generate-ddl: true
    properties:
      hibernate:
        max_fetch_depth: 3
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    org:
      springframework:
        web: debug

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/indiepost?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: indiepost
    password: indiepost
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    org:
      springframework:
        web: debug

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://rds.indiepost.vpc:3306/indiepost?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: indiepost
    password: indiepost
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  redis:
    host: redis.indiepost.vpc
    port: 6379
logging:
  level:
    org:
      springframework:
        web: info
