spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jmx:
    default-domain: newIndiepost
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    properties:
      hibernate:
        search:
          default:
            directory_provider: ram
        max_fetch_depth: 3
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    org:
      springframework:
        web: info

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/indiepost?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&sessionVariables=sql_mode=''&useSSL=false
    username: indiepost
    password: indiepost
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        web: debug

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://indiepost-rds-cluster.cluster-cwrbrz9y9dsp.ap-northeast-2.rds.amazonaws.com:3306/indiepost?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&sessionVariables=sql_mode=''&useSSL=false
    username: indiepost
    password: indiepost
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        web: info
