spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/indiepost?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&sessionVariables=sql_mode=''
    username: indiepost
    password: indiepost
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jmx:
    default-domain: newIndiepost
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: /data/lucene/indexes/
        format_sql: false
        max_fetch_depth: 3
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    org:
      springframework:
        web: info